<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.cam.dbeaver</groupId>
    <artifactId>dbeaver-cubrid</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <properties>
        <tycho.version>4.0.12</tycho.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>

    <modules>
        <module>org.cam.dbeaver.cubrid.export.excel</module>
        <module>org.cam.dbeaver.cubrid.export.excel.feature</module>
    </modules>

    <repositories>
        <repository>
            <id>eclipse-release</id>
            <url>https://download.eclipse.org/releases/latest/</url>
            <layout>p2</layout>
        </repository>
	    <repository>
            <id>dbeaver-ce</id>
            <url>https://dbeaver.io/update/latest/</url>
            <layout>p2</layout>
        </repository>
    </repositories>

    <build>
        <plugins>
            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-maven-plugin</artifactId>
                <version>${tycho.version}</version>
                <extensions>true</extensions>
            </plugin>

            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>target-platform-configuration</artifactId>
                <version>${tycho.version}</version>
                <configuration>
                    <pomDependencies>consider</pomDependencies>
                    <environments>
                        <environment>
                            <os>win32</os>
                            <ws>win32</ws>
                            <arch>x86_64</arch>
                        </environment>
                        <environment>
                            <os>linux</os>
                            <ws>gtk</ws>
                            <arch>x86_64</arch>
                        </environment>
                        <environment>
                            <os>macosx</os>
                            <ws>cocoa</ws>
                            <arch>x86_64</arch>
                        </environment>
                        <environment>
                            <os>macosx</os>
                            <ws>cocoa</ws>
                            <arch>aarch64</arch>
                        </environment>
                    </environments>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-compiler-plugin</artifactId>
                <version>${tycho.version}</version>
                <configuration>
                    <useProjectSettings>false</useProjectSettings>
                    <source>21</source>
                    <target>21</target>
                    <compilerVersion>21</compilerVersion>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
